version: '3.8'

services:
  backend:
    build: .
    container_name: mi-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mi_basedatos
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  mongodb:
    image: mongo:6.0
    container_name: mi-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mi_basedatos
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword

volumes:
  mongo_data:
